// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtXU805yYjCq2q7sT8UWMcu2vRgBJasD4',
    appId: '1:952689714575:web:b70f26e233781d5b8b57fa',
    messagingSenderId: '952689714575',
    projectId: 'smsfirebase-8b2b6',
    authDomain: 'smsfirebase-8b2b6.firebaseapp.com',
    databaseURL: 'https://smsfirebase-8b2b6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smsfirebase-8b2b6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCybGEAOHm4KalXY_ToORD_tOdhAcyVpT0',
    appId: '1:952689714575:android:771f7c162e6ba4d08b57fa',
    messagingSenderId: '952689714575',
    projectId: 'smsfirebase-8b2b6',
    databaseURL: 'https://smsfirebase-8b2b6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smsfirebase-8b2b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXTztSwm_Nyuw3qBK4Absq8zcJfjzCt3c',
    appId: '1:952689714575:ios:dc69fcc5cbdb67268b57fa',
    messagingSenderId: '952689714575',
    projectId: 'smsfirebase-8b2b6',
    databaseURL: 'https://smsfirebase-8b2b6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smsfirebase-8b2b6.appspot.com',
    iosBundleId: 'com.example.smsSql',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXTztSwm_Nyuw3qBK4Absq8zcJfjzCt3c',
    appId: '1:952689714575:ios:dc69fcc5cbdb67268b57fa',
    messagingSenderId: '952689714575',
    projectId: 'smsfirebase-8b2b6',
    databaseURL: 'https://smsfirebase-8b2b6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smsfirebase-8b2b6.appspot.com',
    iosBundleId: 'com.example.smsSql',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtXU805yYjCq2q7sT8UWMcu2vRgBJasD4',
    appId: '1:952689714575:web:98d7c5d79af2391e8b57fa',
    messagingSenderId: '952689714575',
    projectId: 'smsfirebase-8b2b6',
    authDomain: 'smsfirebase-8b2b6.firebaseapp.com',
    databaseURL: 'https://smsfirebase-8b2b6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smsfirebase-8b2b6.appspot.com',
  );
}
